apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
      annotations:
         argocd-notifications.argoproj.io/subscribe.on-sync-succeeded.slack: ""
         argocd-notifications.argoproj.io/subscribe.on-sync-failed.slack: ""
         argocd-notifications.argoproj.io/subscribe.on-deployed.slack: ""
         argocd-notifications.argoproj.io/subscribe.on-health-degraded.slack: ""
         argocd-notifications.argoproj.io/subscribe.on-sync-running.slack: ""
         argocd-notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: ""
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
